{{- if and .Values.phpmyadmin.enabled .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.fullname" . }}-phpmyadmin
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "laravel-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: phpmyadmin
  template:
    metadata:
      labels:
        {{- include "laravel-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: {{ include "laravel-app.mysql.fullname" . }}
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: PMA_PASSWORD
              value: {{ .Values.mysql.auth.password | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-app.fullname" . }}-phpmyadmin
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: phpmyadmin
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  ports:
    - port: {{ .Values.phpmyadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laravel-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: phpmyadmin
{{- end }}
