apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}-env
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.laravel.secrets.APP_KEY }}
  APP_KEY: {{ .Values.laravel.secrets.APP_KEY | b64enc | quote }}
  {{- end }}
  DB_PASSWORD: {{ .Values.laravel.secrets.DB_PASSWORD | b64enc | quote }}
