version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=laravel_password
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: laravel_user
            PMA_PASSWORD: laravel_password
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - laravel-network

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
