apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/component: web-application
    app.kubernetes.io/environment: development
spec:
  project: default
  source:
    repoURL: https://github.com/Grambot-ops/Helm_client_application.git
    targetRevision: HEAD
    path: helm/laravel-app
    helm:
      # Use values file for development environment
      valueFiles:
        - values.yaml
        - values-development.yaml
      parameters:
        - name: image.repository
          value: "laravel-app"
        - name: image.tag
          value: "latest"
        - name: image.pullPolicy
          value: "Never"
        - name: service.type
          value: "NodePort"
        - name: ingress.hosts[0].host
          value: "laravel-app-dev.local"
  destination:
    server: https://kubernetes.default.svc
    namespace: laravel-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Laravel application (Development) deployed via Helm chart from GitHub repository"
    - name: "Repository"
      value: "https://github.com/Grambot-ops/Helm_client_application.git"
    - name: "Environment"
      value: "Development"
