apiVersion: v2
name: laravel-app
description: A Helm chart for Laravel application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - laravel
  - php
  - web
home: https://github.com/your-org/laravel-app
sources:
  - https://github.com/your-org/laravel-app
maintainers:
  - name: Your Name
    email: your.email@example.com
